  // {
  //   "id": 3,
  //   "title": "Loan CRM Dashboard",
  //   "category": "CRM Web Application",
  //   "client": "ProReckon",
  //   "duration": "8 months",
  //   "team": "7 developers",
  //   "year": "2024",
  //   "status": "Live",
  //   "description": "A CRM tool focused on loan origination, tracking, and commission management with real-time dashboards and editable workflows.",
  //   "challenge": "Streamline loan management and commission tracking within a single dashboard for admin users.",
  //   "solution": "Built custom dashboards with editable tables, loan inquiry workflow, document management, and commission calculators.",
  //   "results": [],
  //   "technologies": [],
  //   "features": [
  //     "KPI Dashboards for business and commissions",
  //     "Editable transaction tables",
  //     "Loan lifecycle tracking",
  //     "Client document management"
  //   ],
  //   "image": "/Loan CRM Thumbnail.jpeg",
  //   "gallery": ["/Loan CRM Thumbnail.jpeg","/Loan CRM1.jpeg","/CRM1.png", "/CRM2.png", "/CRM4.png", "/CRM.png"],
  //   "metrics": { "logo": "CRM", "year": "2024", "rating": "4.3" },
  //   "color": "gray",
  //   "bgGradient": "from-gray-100 to-neutral-100",
  //   "testimonial": null,
  //   "liveUrl": "",
  //   "githubUrl": ""
  // },